linters:
  enable:
    - gocognit
    - gocritic
    - gocyclo
    - goerr113
    - golint
    - interfacer
    - prealloc
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 10
