sudo: false

addons:
  apt_packages:
  - libgl1-mesa-dev
  - xorg-dev

services:
- xvfb

language: go

go:
- "1.14"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
