dist: xenial
os: linux
addons:
  apt_packages:
  - libgl1-mesa-dev
  - xorg-dev
services:
- xvfb
language: go
go:
- "1.15"
before_script:
- go get github.com/mattn/goveralls
- "export DISPLAY=:99.0"
- sleep 3 # give xvfb some time to start
after_script:
- go build ./cmd/demo
- goveralls -service=travis-ci
